/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pbo1;

/**
 *
 * @author DYNABOOK
 */
public class FormPendaftaran extends javax.swing.JFrame {

    /**
     * Creates new form FormPendaftaran
     */
    public FormPendaftaran() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        labelnama = new javax.swing.JLabel();
        txtnama = new javax.swing.JTextField();
        txtnomor = new javax.swing.JTextField();
        labelnomor = new javax.swing.JLabel();
        labelkelamin = new javax.swing.JLabel();
        rbuttonlaki = new javax.swing.JRadioButton();
        rbuttonperempuan = new javax.swing.JRadioButton();
        labeljenjang = new javax.swing.JLabel();
        combojenjang = new javax.swing.JComboBox<>();
        labellomba = new javax.swing.JLabel();
        checkolmat = new javax.swing.JCheckBox();
        checkolsains = new javax.swing.JCheckBox();
        checkts = new javax.swing.JCheckBox();
        txtdata = new javax.swing.JTextField();
        buttonreset = new javax.swing.JButton();
        buttonclose = new javax.swing.JButton();
        buttontampil = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(153, 255, 153));
        jPanel1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel1.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        jLabel1.setText("DATA PESERTA");

        labelnama.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        labelnama.setText("Nama");

        txtnama.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N

        txtnomor.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        txtnomor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtnomorActionPerformed(evt);
            }
        });

        labelnomor.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        labelnomor.setText("No Telepon");

        labelkelamin.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        labelkelamin.setText("Jenis Kelamin");

        buttonGroup1.add(rbuttonlaki);
        rbuttonlaki.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        rbuttonlaki.setText("Laki-laki");
        rbuttonlaki.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbuttonlakiActionPerformed(evt);
            }
        });

        buttonGroup1.add(rbuttonperempuan);
        rbuttonperempuan.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        rbuttonperempuan.setText("Perempuan");
        rbuttonperempuan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbuttonperempuanActionPerformed(evt);
            }
        });

        labeljenjang.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        labeljenjang.setText("Jenjang");

        combojenjang.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        combojenjang.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "", "SD", "SMP", "SMA" }));
        combojenjang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                combojenjangActionPerformed(evt);
            }
        });

        labellomba.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        labellomba.setText("Lomba");

        checkolmat.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        checkolmat.setText("Olimpiade Matematika");

        checkolsains.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        checkolsains.setText("Olimpiade Sains");
        checkolsains.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkolsainsActionPerformed(evt);
            }
        });

        checkts.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        checkts.setText("Telling Story");

        txtdata.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N

        buttonreset.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        buttonreset.setText("Reset");

        buttonclose.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        buttonclose.setText("Close");

        buttontampil.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        buttontampil.setText("Tampil");
        buttontampil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttontampilActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtdata)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labelnama)
                            .addComponent(labelnomor)
                            .addComponent(labelkelamin)
                            .addComponent(labeljenjang)
                            .addComponent(labellomba))
                        .addGap(28, 28, 28)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(combojenjang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(checkolmat)
                            .addComponent(checkolsains)
                            .addComponent(checkts)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(rbuttonlaki)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(rbuttonperempuan))
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jLabel1)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(txtnomor, javax.swing.GroupLayout.DEFAULT_SIZE, 155, Short.MAX_VALUE)
                                            .addComponent(txtnama))))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 54, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(buttontampil)
                                    .addComponent(buttonreset)
                                    .addComponent(buttonclose))
                                .addGap(30, 30, 30)))))
                .addGap(18, 18, 18))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelnama)
                    .addComponent(txtnama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonreset))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelnomor)
                    .addComponent(txtnomor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonclose))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelkelamin)
                    .addComponent(rbuttonlaki)
                    .addComponent(rbuttonperempuan)
                    .addComponent(buttontampil))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labeljenjang)
                    .addComponent(combojenjang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labellomba)
                    .addComponent(checkolmat))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(checkolsains)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(checkts)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 13, Short.MAX_VALUE)
                .addComponent(txtdata, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void rbuttonlakiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbuttonlakiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbuttonlakiActionPerformed

    private void rbuttonperempuanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbuttonperempuanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbuttonperempuanActionPerformed

    private void checkolsainsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkolsainsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_checkolsainsActionPerformed

    private void txtnomorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtnomorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtnomorActionPerformed

    private void combojenjangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_combojenjangActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_combojenjangActionPerformed

    private void buttontampilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttontampilActionPerformed
        
    }//GEN-LAST:event_buttontampilActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormPendaftaran.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormPendaftaran.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormPendaftaran.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormPendaftaran.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormPendaftaran().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton buttonclose;
    private javax.swing.JButton buttonreset;
    private javax.swing.JButton buttontampil;
    private javax.swing.JCheckBox checkolmat;
    private javax.swing.JCheckBox checkolsains;
    private javax.swing.JCheckBox checkts;
    private javax.swing.JComboBox<String> combojenjang;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel labeljenjang;
    private javax.swing.JLabel labelkelamin;
    private javax.swing.JLabel labellomba;
    private javax.swing.JLabel labelnama;
    private javax.swing.JLabel labelnomor;
    private javax.swing.JRadioButton rbuttonlaki;
    private javax.swing.JRadioButton rbuttonperempuan;
    private javax.swing.JTextField txtdata;
    private javax.swing.JTextField txtnama;
    private javax.swing.JTextField txtnomor;
    // End of variables declaration//GEN-END:variables
}
